void test_construire_requete_etoile_et_renvoyer_statut_ok();
void test_construire_requete_selection_et_renvoyer_statut_ok();
void test_construire_requete_et_renvoyer_statut_ko();
void test_construire_condition_et_renvoyer_statut_ok ();
void test_prefixer_expression();
void test_transformer_expression_prefixee_en_arbre();
void test_concatener_tests();
void test_construire_requete_join_et_renvoyer_statut_ok();
